Why does the following code...

def execute(block)
  block.call
end

execute { puts "Hello from inside the execute method!" }

Give us the following error when we run it?

block.rb1:in `execute': wrong number of arguments (0 for 1) (ArgumentError)
from test.rb:5:in `<main>'

# The argument "block" doesn't have an ampersand in front of it, so it looks like a normal parameter to the execute method, and not a block of code.
